#spring.application.name=AttendanceApp


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Masato0106
  jpa:
    hibernate:
      ddl-auto: update # 適切な値を設定してください